import { Octokit } from '@octokit/rest';
import fs from 'fs';

const octokit = new Octokit({ 
  auth: process.env.GITHUB_TOKEN 
});

function getRepoInfo() {
  const repo = process.env.GITHUB_REPOSITORY;
  
  if (!repo) {
    throw new Error('GITHUB_REPOSITORY environment variable is not set');
  }

  const [owner, repoName] = repo.split('/');
  
  let prNumber = process.env.PR_NUMBER;
  
  if (!prNumber && process.env.GITHUB_EVENT_PATH) {
    try {
      const eventData = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'));
      prNumber = eventData.pull_request?.number;
    } catch (error) {
      console.warn('Could not read GitHub event file:', error.message);
    }
  }

  if (!prNumber) {
    const refMatch = process.env.GITHUB_REF?.match(/refs\/pull\/(\d+)\//);
    if (refMatch) {
      prNumber = refMatch[1];
    }
  }

  if (!prNumber) {
    throw new Error('Could not determine PR number from environment');
  }

  return { 
    owner, 
    repo: repoName, 
    pull_number: parseInt(prNumber, 10) 
  };
}

export async function getPullRequestDiff() {
  const { owner, repo, pull_number } = getRepoInfo();

  console.log(`Fetching diff for PR #${pull_number} in ${owner}/${repo}`);

  const { data } = await octokit.pulls.get({
    owner,
    repo,
    pull_number,
    mediaType: { format: 'diff' }
  });

  return data;
}

export async function getChangedFiles() {
  const { owner, repo, pull_number } = getRepoInfo();

  console.log(`Fetching changed files for PR #${pull_number}`);

  const { data } = await octokit.pulls.listFiles({
    owner,
    repo,
    pull_number
  });

  return data.map(file => ({
    filename: file.filename,
    status: file.status,
    additions: file.additions,
    deletions: file.deletions,
    changes: file.changes,
    patch: file.patch
  }));
}

export async function postReviewComment(review) {
  const { owner, repo, pull_number } = getRepoInfo();

  const body = formatReviewComment(review);

  console.log(`Posting review comment to PR #${pull_number}`);

  await octokit.pulls.createReview({
    owner,
    repo,
    pull_number,
    event: 'COMMENT',
    body
  });
}

function formatReviewComment(review) {
  let comment = `## AI Code Review\n\n`;
  
  comment += `### Summary\n${review.summary}\n\n`;

  if (review.issues && review.issues.length > 0) {
    comment += `### ⚠️ Issues Found (${review.issues.length})\n\n`;
    
    const critical = review.issues.filter(i => i.severity === 'CRITICAL');
    const high = review.issues.filter(i => i.severity === 'HIGH');
    const medium = review.issues.filter(i => i.severity === 'MEDIUM');
    const low = review.issues.filter(i => i.severity === 'LOW');

    if (critical.length > 0) {
      comment += `#### 🚨 Critical\n`;
      critical.forEach((issue, i) => {
        comment += formatIssue(issue, i + 1);
      });
    }

    if (high.length > 0) {
      comment += `#### 🔴 High Priority\n`;
      high.forEach((issue, i) => {
        comment += formatIssue(issue, i + 1);
      });
    }

    if (medium.length > 0) {
      comment += `#### 🟡 Medium Priority\n`;
      medium.forEach((issue, i) => {
        comment += formatIssue(issue, i + 1);
      });
    }

    if (low.length > 0) {
      comment += `#### 🔵 Low Priority\n`;
      low.forEach((issue, i) => {
        comment += formatIssue(issue, i + 1);
      });
    }
  } else {
    comment += `### No Issues Found\n\nThe code looks good! No significant issues detected.\n\n`;
  }

  if (review.suggestions && review.suggestions.length > 0) {
    comment += `### 💡 Suggestions (${review.suggestions.length})\n\n`;
    review.suggestions.forEach((suggestion, i) => {
      comment += `${i + 1}. ${suggestion}\n`;
    });
    comment += `\n`;
  }

  comment += `---\n`;
  comment += `*Generated by AI Code Reviewer* | Analyzed ${review.reviewCount || 1} section(s)\n`;

  return comment;
}

function formatIssue(issue, index) {
  let formatted = `\n**${index}. ${issue.title}**\n`;
  formatted += `   - ${issue.description}\n`;
  
  if (issue.file) {
    formatted += `   - File: \`${issue.file}\`\n`;
  }
  
  if (issue.line) {
    formatted += `   - Line: ${issue.line}\n`;
  }
  
  if (issue.suggestion) {
    formatted += `   - Suggestion: ${issue.suggestion}\n`;
  }
  
  formatted += `\n`;
  
  return formatted;
}

export default { getPullRequestDiff, getChangedFiles, postReviewComment };